import { Task } from '../../core/models/task';
import { TasksView } from '../../core/models/tasksView';
import { HomeLogicService } from './home.logic.service';

// 1 - S.U.T. WITHOUT dependencies
// Test like any other TypeScript class

describe('Home Logic Service', () => {
  describe('GIVEN: a composeTasksView method ', () => {
    let sut: HomeLogicService;
    let inputTasks: Task[];
    let actual: TasksView;
    beforeEach(() => {
      // Arrange
      sut = new HomeLogicService();
    });
    describe('WHEN called with an empty array', () => {
      beforeEach(() => {
        inputTasks = [];
        // Act
        actual = sut.composeTasksView(inputTasks);
      });
      it('THEN should return a view with ceros', () => {
        // Assert
        const expected: TasksView = { total: 0, pending: 0 };
        expect(actual).toEqual(expected);
      });
    });
    describe('WHEN called with one pending task', () => {
      beforeEach(() => {
        inputTasks = [{ id: '', projectId: '', title: '', done: false }];
        // Act
        actual = sut.composeTasksView(inputTasks);
      });
      it('THEN should return a view with ones', () => {
        // Assert
        const expected: TasksView = { total: 1, pending: 1 };
        expect(actual).toEqual(expected);
      });
    });
    describe('WHEN called with one done task', () => {
      beforeEach(() => {
        inputTasks = [{ id: '', projectId: '', title: '', done: true }];
        // Act
        actual = sut.composeTasksView(inputTasks);
      });
      it('THEN should return a view with one and cero', () => {
        // Assert
        const expected: TasksView = { total: 1, pending: 0 };
        expect(actual).toEqual(expected);
      });
    });
    describe('WHEN called with one done task and two undone', () => {
      beforeEach(() => {
        inputTasks = [
          { id: '', projectId: '', title: '', done: true },
          { id: '', projectId: '', title: '', done: false },
          { id: '', projectId: '', title: '', done: false },
        ];
        // Act
        actual = sut.composeTasksView(inputTasks);
      });
      it('THEN should return a view with three and one', () => {
        // Assert
        const expected: TasksView = { total: 3, pending: 2 };
        expect(actual).toEqual(expected);
      });
    });
  });
});

// ORIGINAL AUTOGENERATED CODE
// describe('Home.LogicService', () => {
//   let service: HomeLogicService;

//   beforeEach(() => {
//     TestBed.configureTestingModule({});
//     service = TestBed.inject(Home.LogicService);
//   });

//   it('should be created', () => {
//     expect(service).toBeTruthy();
//   });
// });
